### ISSUE TITLE
rst:0x10 (RTCWDT_RTC_RESET),boot:0x33 (SPI_FAST_FLASH_BOOT) flash read err, 1000 ets_main.c 371  ets Jun  8 2016 00:22:57

### ISSUE THREAD

**Issue by GeorgeFlorian** [NeoCat/ESP32-P3RGB64x32MatrixPanel#15]
Hello !

I'm using an ESP32 Wroom-32, a SMD 2727 P5 64x32 LED display and 2 Logic Level Converters.

I've soldered the pins as per the default constructor. I've uploaded the following sketch in the ESP and something bizarre happens.  

```
#include <WiFi.h>
#include <Adafruit_GFX.h>
#include <Fonts/FreeSans9pt7b.h>
#include <P3RGB64x32MatrixPanel.h>               
#include <SPI.h>

P3RGB64x32MatrixPanel matrix;
const char* ssid = "ssid";
const char* password = "password";

void setup() {
  Serial.begin(115200);
  delay(1000);
  Serial.println((String)"Attempting to connect to " + ssid);
  WiFi.begin(ssid,password);
  delay(500);
  int k = 0;
  while(WiFi.status() != WL_CONNECTED && k<20) {
    Serial.println((String)"Attempt number: " + (k+1));
    k++;
    delay(1000);
  }
  IPAddress ip = WiFi.localIP();
  if(WiFi.status() != WL_CONNECTED) {
    ESP.restart();
  } else {
    
    Serial.println((String)"Connected to *" + ssid + "* ! IP Address: " + ip.toString());
  }

  matrix.begin();
  delay(500);
  matrix.setTextColor(matrix.color444(180,0,0));
  matrix.setFont(&FreeSans9pt7b);
  matrix.println("IP Address: ");
  matrix.setTextColor(matrix.color444(255,255,255));
  matrix.println(ip);
}

void loop() {

}
```

https://i.postimg.cc/VkCHqbsd/20190401-135241.jpg

The RED (PIN 1) wire from the HUB75 is on R1 (IO25).

I've done the workaround, changing from `PROVIDE ( GPIO = 0x3ff44000 );` to `PROVIDE ( GPIO = 0x60004000 );`

If the ESP32 is half-way inside [(like this)](https://i.postimg.cc/gcXndYgG/20190401-141209.jpg), the screen is [white](https://i.postimg.cc/hPVvz2Fw/20190401-141143.jpg) if I insert it all the way it get's [red](https://i.postimg.cc/1t41G38X/20190401-141233.jpg)

If I reset the ESP, the display will be off, and the Serial Monitor will output:

```
rst:0x10 (RTCWDT_RTC_RESET),boot:0x33 (SPI_FAST_FLASH_BOOT)
flash read err, 1000
ets_main.c 371 
ets Jun  8 2016 00:22:57
```
repeating itself without stopping.

If you are wondering why I need to insert the ESP32 into the board every time it's because I can't upload a sketch when the ESP32 is on the board.

**Comment by NeoCat** [comment]
It might be because not enough power is provided. USB serial is not good power source. Use external power source such as an AC adapter that can provide at least 2A current.

**Comment by GeorgeFlorian** [comment]
> It might be because not enough power is provided. USB serial is not good power source. Use external power source such as an AC adapter that can provide at least 2A current.

These are the specs of my power supply:

https://i.postimg.cc/prt2vnW7/20190401-145102.jpg

I am using 2 Logic Level Converters to shift from 5V to 3V3.

**Comment by NeoCat** [comment]
Or, you might have burned your flash. Check here too:
https://github.com/espressif/esp-idf/issues/117

**Comment by GeorgeFlorian** [comment]
> Or, you might have burned your flash. Check here too:
> [espressif/esp-idf#117](https://github.com/espressif/esp-idf/issues/117)

How can it be burned if I can upload sketches and use the ESP32 when I take it off the board and power it up using a USB Cable ?

**Comment by NeoCat** [comment]
The error is reported at many pages, but I'm not sure why you are suffering the issue. It might be due to your board broken by electrical shock or mis-write the fuse bits, or power source issue, or short in your circuit, or many other reasons. What I can say is only that google by the error message and try many things with your hardware...

**Comment by GeorgeFlorian** [comment]
> The error is reported at many pages, but I'm not sure why you are suffering the issue. It might be due to your board broken by electrical shock or mis-write the fuse bits, or power source issue, or short in your circuit, or many other reasons. What I can say is only that google by the error message and try many things with your hardware...

Do you have any photo of one of your wiring to the LED Display ? I am convinced I soldered the wires appropriately, but having no example and this being the first time doing it, I may have done something wrong.

**Comment by NeoCat** [comment]
Hope this helps...
https://cdn-ak.f.st-hatena.com/images/fotolife/N/NeoCat/20180502/20180502032100.jpg

**Comment by GeorgeFlorian** [comment]
> Hope this helps...
> https://cdn-ak.f.st-hatena.com/images/fotolife/N/NeoCat/20180502/20180502032100.jpg

Dude, this is great ! You have way less wires than I do. I used 2 LLC to shift from 5V to 3V3 but you don't. You connected the GPIO from the ESP straight to the HUB75 and you feed 5V to the ESP... How ? Isn't the ESP supposed to work at 3V3 ? You have nothing connected to the 3V3 pin..

**Comment by NeoCat** [comment]
I am driving the LED matrix directly by the 3.3V signals, but working without any problem so far. The power source is 5V 2A-max AC adapter.

**Comment by GeorgeFlorian** [comment]
> I am driving the LED matrix directly by the 3.3V signals, but working without any problem so far. The power source is 5V 2A-max AC adapter.

I don't know how you did that ! I used Logic Level Converters and it still burned my ESP32.

**Comment by carloHuang** [comment]
Maybe you can check if the esp32 strapping pin is set to the wrong state.I've encountered similar problems.IO12 should be pulled down by default, but my baseboard pulls this IO port up to 3.3V with a resistor.
