### ISSUE TITLE
Rotate the Matrix Display

### ISSUE THREAD

**Issue by Robiv8** [NeoCat/ESP32-P3RGB64x32MatrixPanel#21]
Hallo,
is there a way to rotate the display to 180°
THX

**Comment by NeoCat** [comment]
How about changing
https://github.com/NeoCat/ESP32-P3RGB64x32MatrixPanel/blob/0d55a1348478a6711f6b0ce4b7537a5ce2556b8b/P3RGB64x32MatrixPanel.cpp#L85
to
```C++
  int16_t idx = (63 - x) + (31 - y) * 64;
```
?

**Comment by Robiv8** [comment]
i will try it tomorrow, thanks

**Comment by Robiv8** [comment]
Great! Work
Thanks
