### ISSUE TITLE
How to send a image to esp32

### ISSUE THREAD

**Issue by Robiv8** [NeoCat/ESP32-P3RGB64x32MatrixPanel#22]
The code is working, but I don't no how to send an image to the matrix respective the esp32 from my iMac, MacBook ore iphone?
Any hint ore link
THX

**Comment by NeoCat** [comment]
Read https://github.com/NeoCat/ESP32-P3RGB64x32MatrixPanel/blob/master/examples/ImageFromWiFi/image_sender/README.md

**Comment by Robiv8** [comment]
Oh shame on me
THX
