### ISSUE TITLE
scroll text

### ISSUE THREAD

**Issue by MohamadAlsadi** [NeoCat/ESP32-P3RGB64x32MatrixPanel#23]
how I can make scrolling for string text ?

**Comment by NeoCat** [comment]
Redraw text from different point every 100ms or so.

**Comment by MohamadAlsadi** [comment]
Please give me example

**Comment by NeoCat** [comment]
Again, this library is just provides driver of RGB-matrix for ESP32, so drawing itself is done in Adafruit GFX Library. Please see the example of the library,, e,g,
https://github.com/adafruit/RGB-matrix-Panel/blob/master/examples/scrolltext_16x32/scrolltext_16x32.ino
