### ISSUE TITLE
Pin wiring not actually customisable.

### ISSUE THREAD

**Issue by mrcodetastic** [NeoCat/ESP32-P3RGB64x32MatrixPanel#5]
Hi,

I think I may have found an issue with the binary math for the pin wiring. Using anything but the default generally results in the panel not working.

For example.  Set pinLat to 23 (you will need to shift pinB2 to say 14 or something), and it will result in a bunch of coloured lines - garbage. Swapping pin numbers around can also cause breaks - they're all GPIO pins so I don't know what is going on.

I'm not smart enough to understand this code, but I suspect the subtraction math then binary shifting breaks the REG_WRITE? 

`  REG_WRITE(GPIO_OUT1_W1TS_REG, (1 << (pinOE - 32)) | (1 << (pinLAT - 32)));`

Cheers

**Comment by NeoCat** [comment]
With current implementation, pinLAT and pinOE must be on GPIO32 or larger.
Registers to control GPIO's are 32bit, so pins 0-31 and 32- are on different register.
I'll add note about this restriction to README.md.
