### ISSUE TITLE
Ghosting.

### ISSUE THREAD

**Issue by mrcodetastic** [NeoCat/ESP32-P3RGB64x32MatrixPanel#6]
I'm seeing a bit of ghosting with this Library. It could be due it it's good performance and thus driving the LEDs harder. 

Code from a similar project seems to have resolved this issue by:

`need to turn off OE one clock before latch, otherwise can get ghosting`

https://github.com/pixelmatix/SmartMatrix/blob/teensylc/src/SmartMatrixMultiplexedCalcEsp32_Impl.h

Can you confirm a fix for this library? I notice the OE and LAT pins are written to at the same time, which could be the issue.

**Comment by NeoCat** [comment]
Please try something like:
```
diff --git a/P3RGB64x32MatrixPanel.cpp b/P3RGB64x32MatrixPanel.cpp
index cfe91d4..4face15 100644
--- a/P3RGB64x32MatrixPanel.cpp
+++ b/P3RGB64x32MatrixPanel.cpp
@@ -119,7 +119,11 @@ void IRAM_ATTR P3RGB64x32MatrixPanel::draw() {
         ((y & 4) << (pinC - 2)) | ((y & 8) << (pinD - 3));
   REG_WRITE(GPIO_OUT_REG, out);
 
-  for (int x = 0; x < 8; x++) NOP(); // to wait latch and row switch
+  for (int x = 0; x < 8; x++) NOP(); // to wait row switch
+
+  REG_WRITE(GPIO_OUT1_W1TC_REG, (1 << (pinOE - 32)));
+
+  for (int x = 0; x < 8; x++) NOP(); // to wait latch
 
   REG_WRITE(GPIO_OUT1_W1TC_REG, (1 << (pinOE - 32)) | (1 << (pinLAT - 32)));
 }
```

With my LED matrix I couldn't feel changes ...
(Rather, GND line path seems to have much effect ghosting in my environment.)

**Comment by dpechman** [comment]
![image](https://user-images.githubusercontent.com/1469348/51331965-f7059980-1a61-11e9-8a00-a28baf25c101.png)
for me it looks like this, even after changing the above suggested. It's the same ghosting issue?

> Please try something like:
> 
> ```
> diff --git a/P3RGB64x32MatrixPanel.cpp b/P3RGB64x32MatrixPanel.cpp
> index cfe91d4..4face15 100644
> --- a/P3RGB64x32MatrixPanel.cpp
> +++ b/P3RGB64x32MatrixPanel.cpp
> @@ -119,7 +119,11 @@ void IRAM_ATTR P3RGB64x32MatrixPanel::draw() {
>          ((y & 4) << (pinC - 2)) | ((y & 8) << (pinD - 3));
>    REG_WRITE(GPIO_OUT_REG, out);
>  
> -  for (int x = 0; x < 8; x++) NOP(); // to wait latch and row switch
> +  for (int x = 0; x < 8; x++) NOP(); // to wait row switch
> +
> +  REG_WRITE(GPIO_OUT1_W1TC_REG, (1 << (pinOE - 32)));
> +
> +  for (int x = 0; x < 8; x++) NOP(); // to wait latch
>  
>    REG_WRITE(GPIO_OUT1_W1TC_REG, (1 << (pinOE - 32)) | (1 << (pinLAT - 32)));
>  }
> ```
> 
> With my LED matrix I couldn't feel changes ...
> (Rather, GND line path seems to have much effect ghosting in my environment.)

**Comment by NeoCat** [comment]
That wouldn't be caused by a software problem, but wiring noise issue. Wires need to be as short as possible.Especially, some breadboards cannot support high frequency signals.

**Comment by GeorgeFlorian** [comment]
Did you fix this noise issue ? I am having a similar problem.

![image](https://i.postimg.cc/FFcKjQJm/20190405-183258.jpg)

**Comment by mcpgza** [comment]
I have the same problem, please help.

![20190509_194525](https://user-images.githubusercontent.com/50031926/57475606-eee19c00-7294-11e9-976b-13a99c8a018d.jpg)

**Comment by GeorgeFlorian** [comment]
> I have the same problem, please help.
> 
> ![20190509_194525](https://user-images.githubusercontent.com/50031926/57475606-eee19c00-7294-11e9-976b-13a99c8a018d.jpg)

Switch to [SmartMatrix](https://github.com/pixelmatix/SmartMatrix/tree/teensylc). It's what I did.

Also check their [community](https://community.pixelmatix.com/).

**Comment by mrcodetastic** [comment]
I'd be interested to know if you have this ghosting issue with my library: https://github.com/mrfaptastic/ESP32-RGB64x32MatrixPanel-I2S-DMA

Cheers.

**Comment by mcpgza** [comment]
The problem was the power, now it working fine.

**Comment by mcpgza** [comment]
> I'd be interested to know if you have this ghosting issue with my library: https://github.com/mrfaptastic/ESP32-RGB64x32MatrixPanel-I2S-DMA
> 
> Cheers.

Works fine.
